apiVersion: v1 
kind: Secret
metadata: 
  name: mysqlsecret
  labels:
    env: testing
data: 
  MYSQL_ROOT_PASSWORD: cm9vdHJvb3Q=
  MYSQL_DATABASE: cm9vdHJvb3Q=
  MYSQL_USER: U3U=
  MYSQL_PASSWORD: U2hydXRoaUAxMjM=
---
apiVersion: v1 
kind: Pod
metadata:
  name: secretpod
spec: 
  containers: 
    - name: mysqlpod 
      image: mysql:8
      ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP 
      envFrom:
        - secretRef:
            name: mysqlsecret
            optional: true



