apiVersion: v1
kind: ReplicationController
metadata:
  name: rc 
  labels: 
    env: uat
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    env: uat
  template:
    metadata:
      name: rc 
      labels:
        env: uat
    spec:
      containers:
        - name: rc 
          image: shruthibandi457/gol:3.4
          ports:
            - containerPort: 8080
              protocol: TCP

            
    