apiVersion: v1
kind: Secret
metadata: 
  name: Secret
data: 
  registryname: bmV3YWNyCg==
  loginserver: bmV3YWNyc2guYXp1cmVjci5pbw==
  Username: bmV3YWNyc2g=
  password: MFVSaHFpUXJTTHBodTdjbndnNXB5UVAzbTVPbjdMSy9wRzRGWjhOUDZFK0FDUkRXY3REeA==
---
apiVersion: v1 
kind: Pod
metadata:
  name: secretpod
spec: 
  containers:
    - name: secretpod
      image: newacrsh.azurecr.io/nginx:v1
      containerPort: 80
      envFrom:
        - SecretEnvSource: 
            name: Secret
            optional: true

    