apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    app: web
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: jenkins-rs
      labels:
        app: web
    spec:
      containers:
      - name: jenkins
        image: syedsohail321/jenkins:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: web
spec:
  ports:
  - name: nginx-svc
    port: 8081
    targetPort: 8080
  selector:
    app: web
  type: LoadBalancer