
- name: installing nopcommerce
  hosts: all 
  become: yes
  tasks: 
    - name: installing .net packages
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: installing deb packages
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: installing unzip
      ansible.builtin.apt: 
        name: unzip
        state: present
        update_cache: true
    - name: making directory
      ansible.builtin.file: 
        path: /usr/share/nopCommerce
        state: directory
    - name: downloading nop
      ansible.builtin.get_url: 
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.3/nopCommerce_4.60.3_NoSource_linux_x64.zip
        dest: /usr/share/nopCommerce
    - name: unzip nop 
      ansible.builtin.unarchive:
        src: /usr/share/nopCommerce/nopCommerce_4.60.3_NoSource_linux_x64.zip
        dest: /usr/share/nopCommerce
        remote_src: true
    - name: creating directory bin and logs if doesnot exist
      ansible.builtin.file:
        path: 
          - /usr/share/nopCommerce/bin
          - /usr/share/nopCommerce/logs
        state: directory
    - name: adding user nop 
      ansible.builtin.user:
        name: nop
    - name: adding permissions
      ansible.builtin.file:
        path: /usr/share/nopCommerce
        owner: nop
        group: nop 
        state: directory 
        mode: '0777'
        recurse: true
    - name: copying nop servicefile to nopcommerce path
      ansible.builtin.copy: 
        src: nop.service
        dest: /etc/systemd/system/nop.service
    - name: enabling nop
      ansible.builtin.service: 
        name: nop 
        enabled: true
        state: started

