  - name: exploring facts
    hosts: all
    become: yes
    tasks: 
      - name: printing os 
        ansible.builtin.debug:
          msg: "family: {{ ansible_facts['os_family'] }}"
      - name: printing ipaddress
        ansible.builtin.debug: 
          msg: "ip: {{ eth0['ipv4']['address'] }}"